on: [push]
jobs:
    frontend-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: dagger/dagger-for-github@v8.2.0
              with:
                  call: >-
                      frontend-deploy
                      --directory-arg .
                      --cloudflare-apitoken env://CLOUDFLARE_API_TOKEN
                      --cloudflare-account-id env://CLOUDFLARE_ACCOUNT_ID
                      --project-name ${{ vars.PROJECT_NAME }}
              env:
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    backend-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: dagger/dagger-for-github@v8.2.0
              with:
                  call: >-
                      backend-deploy
                      --directory-arg .
                      --cloudflare-apitoken env://CLOUDFLARE_API_TOKEN
                      --cloudflare-account-id env://CLOUDFLARE_ACCOUNT_ID
              env:
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
